dubbo:
# \u6CE8\u518C\u5E94\u7528
  application:
    name: boot_order_service_consumer
# \u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  monitor:
    protocol: registry
server:
  port: 8082
